### PR TITLE
Add taxonomy descriptions, WGU Taxonomy

### PR DESCRIPTION
**Pull request by bradenmacdonald**
This improves the names and descriptions of the sample taxonomies and imports a taxonomy from WGU that we'd like to use for the initial round of testing.

Ticket: can be considered part of FAL-3531.

### CODE REVIEW

**Comment by bradenmacdonald** [comment]
Note: I found a bug when testing this. If there are more than 10 taxonomies, the Taxonomies page in the MFE only shows the first 10. We'll need to add pagination. (CC @ChrisChV )

**Review by pomegranited — APPROVED** [review]
:+1:

- [x] I tested this by running the generate.py script a few times as described in the README.
- [x] I read through the code
- [x] <strike>I checked for accessibility issues</strike> N/A
- [x] <strike>Includes documentation</strike> N/A
- [x] <strike>User-facing strings are extracted for translation</strike> N/A

**Comment by ChrisChV** [comment]
> Note: I found a bug when testing this. If there are more than 10 taxonomies, the Taxonomies page in the MFE only shows the first 10. We'll need to add pagination.

@bradenmacdonald  Was pagination necessary? At some point I remember we said no. The Figma design also has no pagination. Could we do something similar to the entrypoint of the tags, add a parameter to obtain all the taxonomies?

**Comment by bradenmacdonald** [comment]
@ChrisChV Ah. Sure, if you want to, we can just add `?page_size=500` to the request that the MFE makes to list the taxonomies. Then it solves the problem for now. I tested that locally and it works fine :)

**Pull request merged**
